export { ProductPage } from './UI'
export { ProductCard } from '../../components/ProductCard'
export { TrandingProducts } from '../../modules/TrandingProducts'
export { StyledInput } from '../../UI/StyledInput'
export { useAppDispatch } from '../../hooks/reduxHooks'
export { addProduct } from '../../store/slices/cartSlice'