export { CustomerInfoModal } from './UI'
export { useAppDispatch, useAppSelector } from '../../hooks/reduxHooks'
export { Exit } from '../../UI/ExitModal'
export { open } from '../../store/slices/productsSlice'
export type { CustomerInfo, statusesTS } from './modal/types'
export { getInfo } from './modal/getInfo'
export { statuses } from './modal/statuses'
export { ListLinkBtn } from '../../UI/ListLinkBtn'