export { Products } from './UI'
export type { Product } from './models/types'
export { getShopProducts } from './models/getShopProducts'
export { LazyLoad } from '../../UI/LazyLoading'
export { open, setType, setId, setName } from '../../store/slices/productsSlice'
export { useAppDispatch, useAppSelector } from '../../hooks/reduxHooks'
export { ListLinkBtn } from '../../UI/ListLinkBtn'