export { ShopCustomers } from './UI/index'
export { Search } from '../../UI/Search'
export { getCustomers } from './models/getCustomers'
export type { customer } from './models/types'
export { SimpleBlur } from '../../UI/SimpleBlur'
export { LazyLoad } from '../../UI/LazyLoading'
export { useAppDispatch, useAppSelector } from '../../hooks/reduxHooks'
export { openModal } from '../../store/slices/productsSlice'
export { CustomerInfoModal } from '../../components/CustomerInfoModal'
export { ListLinkBtn } from '../../UI/ListLinkBtn'