export { FlexCenter } from "../../UI/FlexCenter"
export { Header } from "../../components/Header"
export { Footer } from "../../components/Footer"
export { Home } from './UI/'
export { StyledInput } from '../../UI/StyledInput'
export { Categories } from '../../modules/Categories'
export { BestDeals } from '../../modules/BestDeals'
export { ChooseShop } from '../../modules/ChooseShop'
export { MostPopular } from '../../modules/MostPopular'
export { TrandingProducts } from '../../modules/TrandingProducts'